version: "3.8"

services:
  api:
    container_name: api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8001:8000"
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    container_name: pgdb
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine

  celery-worker:
    container_name: celery-worker
    build: .
    command: celery -A setup worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - api

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A setup beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - api

  flower:
    build: .
    command: celery -A setup flower --port=5555
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5556:5555
    depends_on:
      - api
      - redis
      - celery-worker

volumes:
  pgdata: {}