# Generated by Django 4.2.5 on 2023-09-17 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at')),
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_code', models.CharField(max_length=10, unique=True)),
                ('guest_limit', models.PositiveIntegerField(default=1)),
                ('bathroom_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pets_allowed', models.BooleanField(default=True)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('activation_date', models.DateField()),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'db_table': 'property',
                'ordering': ['property_code'],
            },
        ),
    ]
