# Generated by Django 4.2.5 on 2023-09-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='deleted_at',
        ),
    ]
